<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-H6V9FIN" failures="1" tests="2" name="executa.ExecutarIT" time="34.612" errors="0" timestamp="2022-04-24T22:41:21 BRT" skipped="0">
  <testcase classname="executa.ExecutarIT" name="runScenario" time="22.451">
    <failure message="expected [] but found [Your data has been successfully deleted from the database.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [] but found [Your data has been successfully deleted from the database.]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:655)
at org.testng.Assert.assertEquals(Assert.java:665)
at provaSicrediWeb@1.0-SNAPSHOT/paginas.Metodos.validarTexto(Metodos.java:276)
at provaSicrediWeb@1.0-SNAPSHOT/steps.Steps.valido_a_exclusao(Steps.java:111)
at âœ½.valido a exclusao(file:///C:/Users/erick/IdeaProjects/provaSicrediWeb/src/test/resources/features/provaSicredi.feature:30)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="executa.ExecutarIT" name="runScenario" time="12.161"/>
  <system-out/>
</testsuite> <!-- executa.ExecutarIT -->
